version: "1.0"
services:
  contact-list:
    image: contact-list
    container_name: contact-list
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    deploy:
      resources:
        limits:
          memory: 300mb